language: node_js

node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
script:
  - yarn deploy
before_deploy:
  - cd client
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $__GITHUB_TOKEN__
  on:
    branch: feature/chat-start
