language: node_js

node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
before_script:
  - cd client
  - yarn install
script:
  - yarn deploy
on:
  branch: feature/chat-start
# before_deploy:
#   - cd client
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $__GITHUB_TOKEN__

