language: node_js

node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $__GITHUB_TOKEN__
  local_dir: client
  on:
    branch: feature/chat-start
