language: node_js

node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
env:
  - CI=false
github_token: $__GITHUB_TOKEN__
before_script:
  - cd client
  - yarn install
script:
  - echo "skipping tests"
