language: node_js

node_js:
  - 'lts/*'
cache:
  directories:
    - node_modules
env:
  - CI=false
before_script:
  - cd client
  - yarn install
  - yarn build
script:
  - echo "skipping tests"
  # - yarn deploy
deploy:
  github_token: $__GITHUB_TOKEN__
  skip_cleanup: true
  local_dir: client/build
  on:
    branch: feature/chat-start
