language: node_js

node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
before_script:
  - cd packages
  - cd client
  - yarn install
script:
  - echo "skipping tests"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $__GITHUB_TOKEN__
  on:
    branch: feature/workspace-setting
