steps:
  - name: "gcr.io/cloud-builders/yarn"
    args: ["add yarn", "yarn"]
  - name: "gcr.io/cloud-builders/yarn"
    args: ["common:build", "yarn"]
  - name: "ubuntu"
    args: ["cd packages"]
  - name: "ubuntu"
    args: ["cd packages"]
  - name: "ubuntu"
    args: ["cd server"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    timeout: "1600s"

timeout: "3600s"
