steps:
  - name: node
    entrypoint: yarn
    args: ["install"]
  - name: node
    entrypoint: yarn
    args: ["common:build", "yarn"]
  - name: node
    entrypoint: yarn
    args: ["server:build", "yarn"]
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: /packages/server
    args: ["app", "deploy"]
    timeout: "1600s"

timeout: "3600s"
