runtime: nodejs12
env_variables:
  NODE_ENV: 'production'
  DEBUG: 'server:server'
  PORT: '3050'

  DB_HOST: '34.64.167.225'
  DB_USER: 'user_1'
  DB_PW: 'password1'
  DB_NAME: 'kakio'
  DB_PORT: '3307'

  DB_DEV_HOST: '34.64.167.225'
  DB_DEV_USER: 'user_3'
  DB_DEV_PW: 'password3'
  DB_DEV_NAME: 'dev_3'
  DB_DEV_PORT: '3307'

  DB_TEST_HOST: '34.64.167.225'
  DB_TEST_USER: 'user_3'
  DB_TEST_PW: 'password3'
  DB_TEST_NAME: 'test_3'
  DB_TEST_PORT: '3307'

  JWT_SECRET: 'leeparkbae123!@#!#!@'

  REDIS_HOST: '34.64.167.225'
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_DB_DEV: '1'
  REDIS_DB_TEST: '4'
