export enum EventMap {
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  AFTER_LOGIN = 'SOCKET/AFTER_LOGIN',
  JOIN_ROOM = 'SOCKET/JOIN_ROOM',
  CHAT_FROM_CLIENT = 'SOCKET/CHAT_FROM_CLIENT',
  CHAT_FROM_SERVER = 'SOCKET/CHAT_FROM_SERVER',
  LEAVE_ROOM_FROM_CLIENT = 'SOCKET/LEAVE_ROOM_FROM_CLIENT',
  LEAVE_ROOM_FROM_SERVER = 'SOCKET/LEAVE_ROOM_FROM_SERVER',
}

export interface LeaveRoom {
  roomUuid: string
  userUuid: string
}
