export enum EventMap {
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  AFTER_LOGIN = 'SOCKET/AFTER_LOGIN',
  JOIN_ROOM = 'SOCKET/JOIN_ROOM',
  CHAT_FROM_CLIENT = 'SOCKET/CHAT_FROM_CLIENT',
  CHAT_FROM_SERVER = 'SOCKET/CHAT_FROM_SERVER',
}
