runtime: nodejs12
env_variables:
  NODE_OPTIONS: ''
handlers:
  - url: /images
    static_dir: static/images
    http_headers:
      Access-Control-Allow-Origin: https://lee-park-bae-project.github.io
      Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
      Access-Control-Max-Age: 3600
      Access-Control-Allow-Headers: Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Content-Type, Authorization
