# This is a basic workflow to help you get started with Actions

name: Vercel Client Auto Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]') && ! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: now-deployment
        with:
          github-token: ${{ secrets.VERCEL_CLIENT_AUTO_DEPLOY }}
          zeit-token: ${{ secrets.VERCEL_TOKEN }}
          #ZEIT_TEAMID: amond

